import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";

export const metadata: Metadata = {
  title: "Todolist App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="w-full h-full bg-black text-white"
    >
      <body className="w-full h-full">
        <Header />
        <main className="w-full h-full">{children}</main>
      </body>
    </html>
  );
}
